version: '3.8'
services:
  rabbitmq:
    build: ./docker/rabbitmq
    container_name: med-rabbitmq
    restart: always
    environment:
      # Vẫn cần các biến này để tạo user/pass
      # Dùng đúng tên biến của image rabbitmq chính thức
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Database cho Account-service
  db-account:
    image: postgres:17
    container_name: med-db-account
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: account_db
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5435:5432" 
    volumes:
      - postgres_account_data:/var/lib/postgresql/data

  # Database cho Scheduling-service
  db-schedules:
    image: postgres:17
    container_name: med-db-schedules
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: schedules_db
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5433:5432" 
    volumes:
      - postgres_schedules_data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U schedules_user -d schedules_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-auth:
    image: postgres:17
    container_name: med-db-auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: auth_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

volumes:
  postgres_account_data:
  postgres_schedules_data:
  postgres_auth_data:
  rabbitmq_data: {}