import { Doctor, Clinic } from '@/components/specific/schedule/appointment/components/doctor_list/EntityCard';

export const DOCTORS: Doctor[] = [
  {
    id: '1',
    type: 'doctor',
    name: 'John Smith',
    specialty: 'Cardiologist',
    hospital: 'City Hospital',
    gender: 'male',
    availableTimes: [
      { date: '2025-09-16', time: '07:30 - 08:00', isAvailable: true },
      { date: '2025-09-16', time: '08:00 - 08:30', isAvailable: true },
      { date: '2025-09-17', time: '14:00 - 14:30', isAvailable: false },
    ],
  },
  {
    id: '2',
    type: 'doctor',
    name: 'Jane Doe',
    specialty: 'Cardiologist',
    hospital: 'General Hospital',
    gender: 'female',
    availableTimes: [
      { date: '2025-09-16', time: '09:00 - 09:30', isAvailable: true },
      { date: '2025-09-18', time: '17:30 - 18:00', isAvailable: true },
    ],
  },
  {
    id: '3',
    type: 'doctor',
    name: 'Alan Walker',
    specialty: 'Dermatologist',
    hospital: 'Sunshine Clinic',
    gender: 'male',
    availableTimes: [
      { date: '2025-09-17', time: '08:00 - 08:30', isAvailable: true },
      { date: '2025-09-18', time: '10:00 - 10:30', isAvailable: true },
      { date: '2025-09-19', time: '15:00 - 15:30', isAvailable: false },
    ],
  },
  {
    id: '4',
    type: 'doctor',
    name: 'Emily Clark',
    specialty: 'Neurologist',
    hospital: 'City Hospital',
    gender: 'female',
    availableTimes: [
      { date: '2025-09-16', time: '09:30 - 10:00', isAvailable: true },
      { date: '2025-09-20', time: '13:00 - 13:30', isAvailable: true },
    ],
  },
  {
    id: '5',
    type: 'doctor',
    name: 'Michael Brown',
    specialty: 'Pediatrician',
    hospital: 'Green Valley Hospital',
    gender: 'male',
    availableTimes: [
      { date: '2025-09-17', time: '07:00 - 07:30', isAvailable: true },
      { date: '2025-09-18', time: '11:00 - 11:30', isAvailable: true },
    ],
  },
  {
    id: '6',
    type: 'doctor',
    name: 'Olivia Davis',
    specialty: 'Cardiologist',
    hospital: 'General Hospital',
    gender: 'female',
    availableTimes: [
      { date: '2025-09-16', time: '08:30 - 09:00', isAvailable: true },
      { date: '2025-09-19', time: '16:00 - 16:30', isAvailable: false },
    ],
  },
  {
    id: '7',
    type: 'doctor',
    name: 'William Lee',
    specialty: 'Orthopedist',
    hospital: 'Sunshine Clinic',
    gender: 'male',
    availableTimes: [
      { date: '2025-09-18', time: '10:00 - 10:30', isAvailable: true },
      { date: '2025-09-19', time: '14:30 - 15:00', isAvailable: true },
    ],
  },
  {
    id: '8',
    type: 'doctor',
    name: 'Sophia Taylor',
    specialty: 'Dermatologist',
    hospital: 'City Hospital',
    gender: 'female',
    availableTimes: [
      { date: '2025-09-17', time: '09:00 - 09:30', isAvailable: true },
      { date: '2025-09-20', time: '12:00 - 12:30', isAvailable: true },
    ],
  },
  {
    id: '9',
    type: 'doctor',
    name: 'James Wilson',
    specialty: 'Pediatrician',
    hospital: 'Green Valley Hospital',
    gender: 'male',
    availableTimes: [
      { date: '2025-09-16', time: '07:30 - 08:00', isAvailable: true },
      { date: '2025-09-18', time: '13:30 - 14:00', isAvailable: true },
    ],
  },
  {
    id: '10',
    type: 'doctor',
    name: 'Isabella Martinez',
    specialty: 'Neurologist',
    hospital: 'General Hospital',
    gender: 'female',
    availableTimes: [
      { date: '2025-09-17', time: '10:30 - 11:00', isAvailable: true },
      { date: '2025-09-19', time: '15:30 - 16:00', isAvailable: true },
    ],
  },
];

export const CLINICS: Clinic[] = [
  {
    id: 'c1',
    type: 'clinic',
    name: 'Phòng Tim mạch',
    specialty: 'Cardiology',
    hospital: 'Bệnh viện City',
    email: 'cardio@cityhospital.com',
    availableTimes: [
      { date: '2025-09-16', time: '08:00 - 08:30', isAvailable: true },
      { date: '2025-09-18', time: '09:00 - 09:30', isAvailable: true },
    ],
  },
  {
    id: 'c2',
    type: 'clinic',
    name: 'Phòng Da liễu',
    specialty: 'Dermatology',
    hospital: 'Bệnh viện Sunshine',
    email: 'derma@sunshineclinic.com',
    availableTimes: [
      { date: '2025-09-17', time: '10:00 - 10:30', isAvailable: true },
      { date: '2025-09-19', time: '14:00 - 14:30', isAvailable: true },
    ],
  },
  {
    id: 'c3',
    type: 'clinic',
    name: 'Phòng Nhi khoa',
    specialty: 'Pediatrics',
    hospital: 'Bệnh viện Green Valley',
    email: 'pediatrics@greenvalley.com',
    availableTimes: [
      { date: '2025-09-16', time: '07:30 - 08:00', isAvailable: true },
      { date: '2025-09-18', time: '11:00 - 11:30', isAvailable: true },
    ],
  },
  {
    id: 'c4',
    type: 'clinic',
    name: 'Phòng Hô hấp',
    specialty: 'Pulmonology',
    hospital: 'Bệnh viện Blue Sky',
    email: 'pulmo@bluesky.com',
    availableTimes: [
      { date: '2025-09-17', time: '09:00 - 09:30', isAvailable: true },
      { date: '2025-09-19', time: '13:00 - 13:30', isAvailable: true },
    ],
  },
  {
    id: 'c5',
    type: 'clinic',
    name: 'Phòng Thần kinh',
    specialty: 'Neurology',
    hospital: 'Bệnh viện Sunrise',
    email: 'neuro@sunrise.com',
    availableTimes: [
      { date: '2025-09-18', time: '08:30 - 09:00', isAvailable: true },
      { date: '2025-09-20', time: '15:00 - 15:30', isAvailable: true },
    ],
  },
  {
    id: 'c6',
    type: 'clinic',
    name: 'Phòng Nội tiết',
    specialty: 'Endocrinology',
    hospital: 'Bệnh viện Green Leaf',
    email: 'endocrine@greenleaf.com',
    availableTimes: [
      { date: '2025-09-16', time: '10:00 - 10:30', isAvailable: true },
      { date: '2025-09-19', time: '14:30 - 15:00', isAvailable: true },
    ],
  },
  {
    id: 'c7',
    type: 'clinic',
    name: 'Phòng Tiêu hóa',
    specialty: 'Gastroenterology',
    hospital: 'Bệnh viện Horizon',
    email: 'gastro@horizon.com',
    availableTimes: [
      { date: '2025-09-17', time: '07:30 - 08:00', isAvailable: true },
      { date: '2025-09-18', time: '11:30 - 12:00', isAvailable: true },
    ],
  },
  {
    id: 'c8',
    type: 'clinic',
    name: 'Phòng Sản phụ khoa',
    specialty: 'Obstetrics & Gynecology',
    hospital: 'Bệnh viện Lotus',
    email: 'obgyn@lotus.com',
    availableTimes: [
      { date: '2025-09-16', time: '08:00 - 08:30', isAvailable: true },
      { date: '2025-09-19', time: '13:00 - 13:30', isAvailable: true },
    ],
  },
];
