export enum NotificationType {
  DOSE_REMINDER = 'DOSE_REMINDER',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  RESULT_AVAILABLE = 'RESULT_AVAILABLE',
  PAYMENT_DUE = 'PAYMENT_DUE',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  GENERAL_ANNOUNCEMENT = 'GENERAL_ANNOUNCEMENT',
}